 -- Andreas "Syranide" Svensson's editor for Wire Expression 2
 -- edited by DarKSunrise aka Assassini
 -- to work with Luapad and with Lua-syntax
 -- edited by Wyozi with auto completion, GM13 fixes and massive refactoring